---
# Read the Docs configuration file for HFortix
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Install all split packages so autodoc can import them
      - pip install -e packages/core
      - pip install -e packages/fortios
      - pip install -e packages/meta

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    # Install the core package
    - method: pip
      path: packages/core
    # Install the fortios package
    - method: pip
      path: packages/fortios
    # Install the meta package
    - method: pip
      path: packages/meta
    # Install documentation dependencies
    - requirements: docs/requirements.txt

# Build PDF and ePub formats in addition to HTML
formats:
  - pdf
  - epub
