---
# Read the Docs configuration file for HFortix-Core
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_build:
      - echo "Build completed successfully"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    # Install this package in editable mode
    - method: pip
      path: .
      extra_requirements:
        - docs
    # Install documentation dependencies
    - requirements: docs/requirements.txt

# Disable PDF/ePub to speed up build (HTML only)
# formats:
#   - pdf
#   - epub
