"""
Pydantic Models for MONITOR - fortiview/historical_statistics

Runtime validation models for fortiview/historical_statistics configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "HistoricalStatisticsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T11:24:37.075239Z
# ============================================================================