"""
Pydantic Models for MONITOR - fortiguard/redirect_portal

Runtime validation models for fortiguard/redirect_portal configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "RedirectPortalModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T11:24:36.857167Z
# ============================================================================